name: Cypress Tests
on: 
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        
        browser: [chrome, firefox, edge]
       
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          browser: ${{ matrix.browser }}
          parallel: true 
          group: "Tests on ${{ matrix.browser }}"
          artifact-paths: "cypress/screenshots/**,cypress/videos/**"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
         
          CYPRESS_baseUrl: "https://www.saucedemo.com"

      - name: Upload test results
        if: always() # Executa mesmo se os testes falharem
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results-${{ matrix.browser }}-${{ github.run_id }}
          path: |
            cypress/screenshots/
            cypress/videos/
            cypress/results/